#!/bin/bash
# Definition des alias raccourcis
alias cdt='cd ~/test/'

# Definition des alias de compilation
alias gccf="gcc -Wall -Wextra -Werror"
alias g++f="g++ -Wall -Wextra -Werror"

# Definition des alias
alias purgevim="rm -f $HOME/.config/nvim/tmp/*"

alias ta="tmux attach"

# Replace ls with exa
exa $HOME >/dev/null 2>&1
if [[ $? == 0 ]]; then
    unalias ls
    unalias ll
    unalias la
    unalias lah
    unalias lh
    alias ls=exa
    alias ll="ls -l --group --git"
    alias la="ll -a"
    alias lg="ll --grid"
    alias lt="ll --tree"
fi

which nvim 2>&1 > /dev/null
if [[ $? == 0 ]]; then
    alias vim=nvim
fi

# School only aliases
if [[ -n $C_SCHOOL ]]; then
    # misc
    alias auteur="echo '$USER' > auteur"
    alias libft="cp -r $LIB .; rm -rf libft/.git"

    # cd alias
    alias cdc='cd ~/Rendu'
    alias cdl="cd $LIB"
    alias cds="cd ~/$C_PATH_TO_PERSONAL_CONFIG/scripts/"

    # compil alias
    alias gccl="gcc -I $LIB/includes -L $LIB -lft"
    alias gcclf="gcc -Wall -Wextra -Werror -I $LIB/includes -L $LIB -lft"
fi
